name: a-release-linux-x64

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'

jobs:
  bundle_linux_x86_64:
    runs-on: ubuntu-22.04
    env:
      CARGO_INCREMENTAL: 0
      CC: clang-18
      CXX: clang++-18
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        clean: false

    - name: Install clang-18
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        sudo apt-get install -y clang-18

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v2-rust"
        shared-key: "zed-linux-x64"
        workspaces: "."
        cache-on-failure: true
        cache-bin: false
        save-if: true

    - name: Setup Linux dependencies
      run: ./script/linux

    - name: Download WASI SDK
      run: ./script/download-wasi-sdk

    - name: Build and bundle
      run: ./script/bundle-linux

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zed-linux-x86_64.tar.gz
        path: target/release/zed-linux-x86_64.tar.gz
        if-no-files-found: error

    timeout-minutes: 120

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}
